server:
    port: 8080
    context-path: /dxk-framework/api
    sessionTimeout: 30

spring:
    profiles:
        active: @{profile-id}

rabbit:
  username: @{rabbit.username}
  password: @{rabbit.password}
  vhost: @{rabbit.vhost}
  demo.exchange: @{rabbit.demo.exchange}
  demo.queue: @{rabbit.demo.queue}
  demo.routingKey: @{rabbit.demo.routingKey}
  demo.pattern: @{rabbit.demo.pattern}

druid:
     url: @{druid.url}
     username: @{druid.username}
     password: @{druid.password}
     filters: @{druid.filters}
     initialSize: '10'
     minIdle: '20'
     maxActive: '50'
     testWhileIdle: 'true'
     connectionProperties: 'druid.stat.slowSqlMillis=1000'

mybatis:
    basePackage: com.demo.mapper
    mapperLocations: classpath*:/mapper/**/*.xml
    typeAliasesPackage: com.demo.model

