server:
    port: 8081
    context-path: /dxk-framework/api
    sessionTimeout: 30

spring:
    profiles:
        active: @{profile-id}
    dubbo:
        appname: dxk-framework
        registry: localhost:2181
        protocol: dubbo
        port: 20880

rabbit:
  addresses: @{rabbit.addresses}
  username: @{rabbit.username}
  password: @{rabbit.password}
  demo.exchange: @{rabbit.demo.exchange}
  demo.queue1: @{rabbit.demo.queue1}
  demo.queue2: @{rabbit.demo.queue2}
  demo.pattern1: @{rabbit.demo.pattern1}
  demo.pattern2: @{rabbit.demo.pattern2}

druid:
     url: @{druid.url}
     username: @{druid.username}
     password: @{druid.password}

mybatis:
    mapperLocations: classpath*:/mapper/**/*.xml
    typeAliasesPackage: com.demo.model
    configLocation: classpath:/mybatis/spring-mybatis.xml
